- uses: keithweaver/aws-s3-github-action@v1.0.0
  with:
    command: cp
    source: ./local_file.txt
    destination: s3://wsi-atena-102-test/github-actions-result//Access_logs.csv
    aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws_region: us-east-1
