uses: cebollia/athena-query-action@v1.0
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
with:
  sql-input: 'CREATE EXTERNAL TABLE IF NOT EXISTS wsiTable(test VARCHAR(255)) LOCATION 's3://wsi-atena-102-test/', SELECT split_part(test, ' ', 9) AS server_status, split_part(test, ' ', 10) AS response_status FROM wsiTable;'
  ddb-id: 'test'
  ddb-table: 'test'
  wait: 'false'
